
## !pip install pandas

In [4]:
import pandas as pd
print(pd.__version__)

2.3.3

In [5]:
import pandas as pd

data = {
    "Name": ["A", "B", "C"],
    "Age": [20, 21, 22]
}

df = pd.DataFrame(data)
print(df)

  Name  Age
0    A   20
1    B   21
2    C   22

In [7]:
!pip install pandas numpy faker openpyxl

Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: faker in c:\programdata\anaconda3\lib\site-packages (40.8.0)
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [9]:
import pandas as pd
import numpy as np
from faker import Faker
import random

In [10]:
fake = Faker()

emr_data = []

for i in range(500):
    emr_data.append({
        "Patient_ID": i+1,
        "Name": fake.name(),
        "Age": random.randint(1,80),
        "Gender": random.choice(["Male","Female"]),
        "Phone": fake.phone_number(),
        "Disease": random.choice(["Cataract","Glaucoma","Diabetes","Normal","Retina"]),
        "Visit_Date": fake.date(),
        "Doctor": random.choice(["Dr.A","Dr.B","Dr.C"]),
        "Hospital": "Eye Hospital"
    })

emr_df = pd.DataFrame(emr_data)

emr_df.to_excel("emr_data.xlsx", index=False)

print("EMR Data Generated")
emr_df.head()

EMR Data Generated

,Patient_ID,Name,Age,Gender,Phone,Disease,Visit_Date,Doctor,Hospital
0,1,Stacy House,7,Male,(745)863-4849x80237,Cataract,1992-05-17,Dr.A,Eye Hospital
1,2,Joseph Schneider,75,Female,290.317.0166,Glaucoma,1986-05-30,Dr.A,Eye Hospital
2,3,Andrea Hill,22,Female,+1-369-508-8940x9297,Cataract,2000-12-01,Dr.B,Eye Hospital
3,4,Molly Davis,71,Male,(470)282-9036,Cataract,2013-11-25,Dr.B,Eye Hospital
4,5,Christopher Davis,2,Male,350.353.2089x061,Retina,1982-07-29,Dr.C,Eye Hospital

In [11]:
print(emr_df.shape)

(500, 9)

In [12]:
emr_df.head(10)

,Patient_ID,Name,Age,Gender,Phone,Disease,Visit_Date,Doctor,Hospital
0,1,Stacy House,7,Male,(745)863-4849x80237,Cataract,1992-05-17,Dr.A,Eye Hospital
1,2,Joseph Schneider,75,Female,290.317.0166,Glaucoma,1986-05-30,Dr.A,Eye Hospital
2,3,Andrea Hill,22,Female,+1-369-508-8940x9297,Cataract,2000-12-01,Dr.B,Eye Hospital
3,4,Molly Davis,71,Male,(470)282-9036,Cataract,2013-11-25,Dr.B,Eye Hospital
4,5,Christopher Davis,2,Male,350.353.2089x061,Retina,1982-07-29,Dr.C,Eye Hospital
5,6,Samantha Salazar,19,Female,001-670-619-8606,Cataract,1974-06-14,Dr.A,Eye Hospital
6,7,Jason Summers,69,Male,001-437-978-5692x8527,Glaucoma,1999-09-15,Dr.B,Eye Hospital
7,8,Michael Madden,76,Male,2593287687,Cataract,2004-06-02,Dr.A,Eye Hospital
8,9,David Porter,73,Female,+1-697-664-5699x77273,Retina,2017-02-09,Dr.A,Eye Hospital
9,10,Andrew Cervantes,6,Male,001-990-870-5089x6960,Glaucoma,2014-01-06,Dr.A,Eye Hospital

In [13]:
emr_df.tail()

,Patient_ID,Name,Age,Gender,Phone,Disease,Visit_Date,Doctor,Hospital
495,496,Mark Soto,47,Male,933-900-0057x55533,Diabetes,2023-10-23,Dr.A,Eye Hospital
496,497,Mrs. Victoria Young DDS,30,Female,3667605983,Glaucoma,1980-11-18,Dr.B,Eye Hospital
497,498,Alexandria Lopez,75,Male,001-935-510-9534,Retina,2023-12-24,Dr.B,Eye Hospital
498,499,Christian Robertson,23,Male,(588)514-6661x1247,Glaucoma,1972-03-17,Dr.C,Eye Hospital
499,500,Jennifer Ford,48,Male,001-955-588-2422x577,Cataract,2008-06-18,Dr.C,Eye Hospital

In [15]:
pd.set_option('display.max_rows', 500)
emr_df

,Patient_ID,Name,Age,Gender,Phone,Disease,Visit_Date,Doctor,Hospital
0,1,Stacy House,7,Male,(745)863-4849x80237,Cataract,1992-05-17,Dr.A,Eye Hospital
1,2,Joseph Schneider,75,Female,290.317.0166,Glaucoma,1986-05-30,Dr.A,Eye Hospital
2,3,Andrea Hill,22,Female,+1-369-508-8940x9297,Cataract,2000-12-01,Dr.B,Eye Hospital
3,4,Molly Davis,71,Male,(470)282-9036,Cataract,2013-11-25,Dr.B,Eye Hospital
4,5,Christopher Davis,2,Male,350.353.2089x061,Retina,1982-07-29,Dr.C,Eye Hospital
5,6,Samantha Salazar,19,Female,001-670-619-8606,Cataract,1974-06-14,Dr.A,Eye Hospital
6,7,Jason Summers,69,Male,001-437-978-5692x8527,Glaucoma,1999-09-15,Dr.B,Eye Hospital
7,8,Michael Madden,76,Male,2593287687,Cataract,2004-06-02,Dr.A,Eye Hospital
8,9,David Porter,73,Female,+1-697-664-5699x77273,Retina,2017-02-09,Dr.A,Eye Hospital
9,10,Andrew Cervantes,6,Male,001-990-870-5089x6960,Glaucoma,2014-01-06,Dr.A,Eye Hospital
10,11,Ronald Pope,4,Female,+1-963-409-6897,Cataract,2010-04-22,Dr.A,Eye Hospital
11,12,Debra Miller,9,Male,001-320-826-5749x330,Normal,2001-09-10,Dr.B,Eye Hospital
12,13,Erica Robinson,11,Female,710-285-1285x97463,Glaucoma,1997-12-03,Dr.B,Eye Hospital
13,14,Meredith Taylor,9,Female,659.878.3186,Retina,2024-01-01,Dr.C,Eye Hospital
14,15,Mary York,46,Male,9422988865,Diabetes,1983-03-18,Dr.C,Eye Hospital
15,16,Christopher Smith,61,Male,+1-821-815-4973,Diabetes,1998-04-18,Dr.C,Eye Hospital
16,17,Joshua Davis,45,Male,+1-584-894-3503x3023,Retina,2009-02-12,Dr.A,Eye Hospital
17,18,John Coleman,24,Female,+1-315-682-9651x15102,Diabetes,1998-01-27,Dr.C,Eye Hospital
18,19,Heather Hernandez,21,Female,001-959-428-6318x617,Diabetes,1995-04-08,Dr.A,Eye Hospital
19,20,Erica Martin,34,Male,624.415.2444,Normal,2017-01-03,Dr.B,Eye Hospital
20,21,Sharon Sawyer,73,Male,(728)508-3037x012,Cataract,1997-11-20,Dr.A,Eye Hospital
21,22,Eric Gay,42,Female,(609)609-4396,Cataract,1993-04-08,Dr.A,Eye Hospital
22,23,Justin Beck,32,Male,768-828-6736x2379,Cataract,1984-08-02,Dr.B,Eye Hospital
23,24,Brittany Vargas,66,Female,(955)425-1210x97913,Cataract,1989-08-10,Dr.C,Eye Hospital
24,25,Clinton Owens,36,Male,001-420-642-7180x037,Retina,2024-11-28,Dr.A,Eye Hospital
25,26,Debra Glover,10,Female,793-859-5665x141,Retina,2014-01-10,Dr.B,Eye Hospital
26,27,Kevin Herring,49,Male,560.221.5766x4203,Retina,1993-09-26,Dr.B,Eye Hospital
27,28,Steven Larson,7,Male,877.713.6448x336,Cataract,1975-04-04,Dr.C,Eye Hospital
28,29,William Curtis,32,Female,(381)890-7850x1271,Cataract,1971-05-13,Dr.B,Eye Hospital
29,30,Deanna Maxwell,67,Male,+1-845-588-3859x6162,Diabetes,1975-01-09,Dr.A,Eye Hospital
30,31,Gary Costa,31,Female,001-902-835-5941,Diabetes,2024-02-13,Dr.B,Eye Hospital
31,32,Corey Williams,48,Female,930.395.0350x51323,Cataract,2019-12-29,Dr.C,Eye Hospital
32,33,Diana Gordon,22,Female,001-501-740-1019x00787,Glaucoma,1994-01-30,Dr.A,Eye Hospital
33,34,Kristina Clarke,77,Male,241.676.0355,Glaucoma,1986-04-11,Dr.B,Eye Hospital
34,35,David Barnes,47,Female,001-982-760-2455x6840,Normal,1994-03-13,Dr.B,Eye Hospital
35,36,Paul Vaughn,42,Male,(642)975-5792x71707,Normal,1988-07-09,Dr.B,Eye Hospital
36,37,Mark Calhoun,31,Female,842.241.9002x94253,Normal,2020-08-21,Dr.B,Eye Hospital
37,38,Thomas Bush,68,Male,273.439.4268x57608,Cataract,1982-01-31,Dr.B,Eye Hospital
38,39,Jeffrey Smith,76,Male,9414240419,Glaucoma,2009-10-20,Dr.A,Eye Hospital
39,40,Adam Lester,78,Female,+1-590-691-2926,Diabetes,1986-12-29,Dr.C,Eye Hospital
40,41,Juan Howard,1,Male,3469948761,Glaucoma,2000-10-09,Dr.C,Eye Hospital
41,42,Mia Welch,36,Female,(253)650-2969x4642,Normal,1984-09-05,Dr.B,Eye Hospital
42,43,Eric Mcintosh,80,Male,+1-302-449-0606x9435,Cataract,2012-07-16,Dr.B,Eye Hospital
43,44,Chad Sherman,13,Female,+1-334-610-1145x30439,Diabetes,1997-10-27,Dr.A,Eye Hospital
44,45,Daniel Wolfe,4,Male,(233)975-0546x0095,Diabetes,2024-01-27,Dr.C,Eye Hospital
45,46,Katie Watson,78,Male,001-770-990-6824x424,Glaucoma,2025-07-20,Dr.A,Eye Hospital
46,47,Christina Alvarez,73,Female,7478837572,Normal,1982-05-27,Dr.B,Eye Hospital
47,48,Samantha Rivera,42,Female,409-232-4310x1877,Retina,1975-09-07,Dr.C,Eye Hospital
48,49,Betty Kane,18,Female,001-965-313-8272,Retina,1990-11-07,Dr.C,Eye Hospital
49,50,Courtney Reid,11,Female,(956)455-8890,Normal,2011-02-20,Dr.B,Eye Hospital
50,51,Kayla Miller,48,Female,001-543-438-2171,Glaucoma,1984-03-08,Dr.C,Eye Hospital
51,52,Christopher Morrow,19,Female,001-540-654-7490x86804,Retina,1976-02-13,Dr.B,Eye Hospital
52,53,Connie Smith,75,Male,+1-448-223-4187,Glaucoma,2015-04-10,Dr.A,Eye Hospital
53,54,David Mcdaniel,1,Male,001-458-937-4187x743,Retina,1970-05-14,Dr.B,Eye Hospital
54,55,Francisco Avila,3,Female,(277)498-7170x75195,Cataract,1979-10-15,Dr.C,Eye Hospital
55,56,Douglas Simpson,17,Male,+1-503-731-1326x344,Glaucoma,2014-03-16,Dr.B,Eye Hospital
56,57,Jennifer Robinson,17,Female,272-595-7155x90132,Glaucoma,1979-02-27,Dr.B,Eye Hospital
57,58,Kevin Patrick,17,Female,001-688-459-3497x4985,Glaucoma,2008-08-13,Dr.B,Eye Hospital
58,59,Sarah Nelson,61,Female,+1-334-545-8838,Retina,1971-12-17,Dr.A,Eye Hospital
59,60,Caleb Jones,67,Male,+1-240-519-4940x927,Diabetes,2005-02-19,Dr.B,Eye Hospital
60,61,Jennifer Pace,22,Male,330-808-9136x8708,Glaucoma,1984-05-10,Dr.B,Eye Hospital
61,62,Elizabeth Boyer,39,Female,999.541.4992,Retina,2018-01-12,Dr.C,Eye Hospital
62,63,Ms. Patricia Davis PhD,42,Male,(283)283-1859x15849,Diabetes,2009-09-16,Dr.A,Eye Hospital
63,64,Jill Carroll,43,Female,+1-477-440-9629x008,Diabetes,1977-07-29,Dr.C,Eye Hospital
64,65,Kristin Nguyen,80,Female,+1-703-254-7537,Cataract,2017-09-24,Dr.C,Eye Hospital
65,66,Raymond Roman,5,Female,+1-412-578-7966,Retina,1979-06-07,Dr.C,Eye Hospital
66,67,Emily Cook,14,Male,951-290-1356,Normal,2013-12-31,Dr.B,Eye Hospital
67,68,Dana Fischer,54,Male,912.414.5157x093,Cataract,1995-10-04,Dr.A,Eye Hospital
68,69,Stephanie Kim,5,Female,001-253-319-5180x120,Cataract,2017-11-17,Dr.A,Eye Hospital
69,70,Jessica Johnson,60,Male,620-352-1540,Diabetes,1999-04-06,Dr.C,Eye Hospital
70,71,Pamela Leonard,27,Male,001-942-422-6634x8667,Diabetes,2016-01-12,Dr.A,Eye Hospital
71,72,Richard Briggs,21,Male,924-612-1684x82544,Retina,1994-09-03,Dr.C,Eye Hospital
72,73,Bruce Holloway,65,Male,(737)801-8821,Cataract,2005-07-31,Dr.B,Eye Hospital
73,74,Sandra Murillo,29,Male,(249)264-8444,Diabetes,1997-05-08,Dr.C,Eye Hospital
74,75,Dustin Schultz,44,Female,001-541-782-0695x79018,Glaucoma,1985-01-23,Dr.C,Eye Hospital
75,76,Stephen Mata,39,Male,+1-760-469-9556x7755,Retina,2003-12-04,Dr.C,Eye Hospital
76,77,Jason Rogers,42,Female,+1-972-423-4450x872,Cataract,1971-11-12,Dr.B,Eye Hospital
77,78,Robert Turner,6,Male,(717)617-2005x0469,Diabetes,1977-09-03,Dr.A,Eye Hospital
78,79,Don Murillo,58,Male,4287141904,Diabetes,1990-08-18,Dr.C,Eye Hospital
79,80,Diana Turner,22,Male,001-819-205-3016x786,Diabetes,1974-02-03,Dr.A,Eye Hospital
80,81,Mitchell Gibson,67,Female,878.825.5969,Normal,2024-02-25,Dr.A,Eye Hospital
81,82,David Santana,51,Male,+1-829-819-5713x981,Retina,2013-02-28,Dr.C,Eye Hospital
82,83,John Williamson,17,Male,573.218.1889x918,Diabetes,1991-08-22,Dr.B,Eye Hospital
83,84,Cody Gordon,67,Male,785.849.9208x75949,Normal,2013-04-03,Dr.C,Eye Hospital
84,85,Christina Johnson,22,Male,502-727-2590x971,Normal,2015-02-28,Dr.C,Eye Hospital
85,86,Jacob Hill,74,Male,(319)398-0478x5489,Normal,1974-12-16,Dr.C,Eye Hospital
86,87,Phyllis Gutierrez,57,Male,3369675422,Glaucoma,2008-08-08,Dr.A,Eye Hospital
87,88,Patrick Atkinson,71,Male,(444)755-9260,Retina,2006-12-27,Dr.B,Eye Hospital
88,89,Jeremy Avila,18,Male,(538)276-4156,Glaucoma,1982-12-12,Dr.B,Eye Hospital
89,90,Philip Baker,10,Male,+1-270-587-0993x880,Retina,2021-01-19,Dr.A,Eye Hospital
90,91,Caleb White,71,Female,906-940-4016x22032,Retina,2020-01-01,Dr.A,Eye Hospital
91,92,Jesse Zamora,67,Male,(518)556-9185,Diabetes,1997-01-18,Dr.B,Eye Hospital
92,93,Susan Smith,23,Male,3923280538,Normal,2006-06-14,Dr.A,Eye Hospital
93,94,Penny Barton,57,Female,001-609-995-5274,Retina,1982-05-18,Dr.A,Eye Hospital
94,95,Joy Ray,21,Male,393.578.7377x9095,Retina,1982-08-31,Dr.C,Eye Hospital
95,96,Crystal Phillips,72,Female,+1-967-440-1432x62414,Glaucoma,1981-11-25,Dr.A,Eye Hospital
96,97,Laura Richardson,68,Female,001-662-959-8319,Diabetes,2018-08-24,Dr.C,Eye Hospital
97,98,Mr. Jesus Kirby,72,Female,+1-555-643-7544x3535,Retina,1988-04-27,Dr.A,Eye Hospital
98,99,Jenna Kelley,64,Female,936.614.4637x2011,Retina,1997-11-17,Dr.A,Eye Hospital
99,100,Melody Lloyd,61,Female,+1-340-289-7565,Retina,2021-03-29,Dr.B,Eye Hospital
100,101,Isabel Robinson,6,Female,(295)327-9067x1034,Glaucoma,1997-06-13,Dr.B,Eye Hospital
101,102,Vanessa Merritt,72,Female,766-491-4956,Normal,2013-12-10,Dr.B,Eye Hospital
102,103,Calvin Davis,54,Female,964-310-1328x73405,Retina,2009-09-30,Dr.B,Eye Hospital
103,104,Marie Rodriguez,39,Female,001-810-885-9732x9784,Diabetes,1983-07-02,Dr.A,Eye Hospital
104,105,Richard Oconnell,27,Male,544-544-1864x18916,Retina,1989-04-25,Dr.C,Eye Hospital
105,106,Courtney Williams,15,Male,001-581-329-7442x46012,Cataract,2013-08-02,Dr.A,Eye Hospital
106,107,Olivia Tanner,4,Female,(879)236-1519x216,Cataract,2010-02-03,Dr.B,Eye Hospital
107,108,Kelsey Snyder,54,Male,987-963-2982,Glaucoma,1982-08-11,Dr.C,Eye Hospital
108,109,Lori Pope,43,Female,4436638172,Glaucoma,1972-10-28,Dr.A,Eye Hospital
109,110,Tony Riggs,4,Male,381.268.9614x87356,Glaucoma,2006-09-22,Dr.A,Eye Hospital
110,111,Andrew Chavez,27,Female,3772322564,Glaucoma,2020-01-08,Dr.C,Eye Hospital
111,112,Felicia Jones,22,Male,001-737-572-5276x01353,Glaucoma,2014-09-12,Dr.A,Eye Hospital
112,113,Lee Hall,28,Female,+1-512-814-9725,Normal,1991-05-15,Dr.C,Eye Hospital
113,114,Kimberly Morrison,21,Male,308-788-0546,Normal,1987-04-17,Dr.C,Eye Hospital
114,115,Chelsea Coleman,55,Female,301.839.0136x57145,Glaucoma,2003-11-01,Dr.C,Eye Hospital
115,116,Bruce Anderson,48,Male,9915628851,Diabetes,2024-11-13,Dr.A,Eye Hospital
116,117,David Sanchez,32,Female,001-814-642-9333,Diabetes,1993-07-05,Dr.B,Eye Hospital
117,118,Carol Tate,64,Female,390.512.6828x98707,Cataract,2024-04-29,Dr.C,Eye Hospital
118,119,Jeremy Palmer,48,Female,884-387-6303x1451,Cataract,1990-07-17,Dr.B,Eye Hospital
119,120,Cathy Lambert,60,Female,001-445-425-1311x53324,Diabetes,1992-08-29,Dr.B,Eye Hospital
120,121,Kyle White,57,Female,2768265740,Retina,1987-06-29,Dr.C,Eye Hospital
121,122,Timothy Gonzales,24,Female,368.345.6333x93918,Normal,1979-06-18,Dr.C,Eye Hospital
122,123,Richard Smith,78,Male,(565)739-8815x827,Diabetes,1995-06-24,Dr.C,Eye Hospital
123,124,Jessica Rodriguez,34,Male,475.597.5224x22436,Glaucoma,1990-08-14,Dr.B,Eye Hospital
124,125,Jasmine Oliver,67,Male,(818)830-1877x67865,Normal,2013-04-03,Dr.B,Eye Hospital
125,126,Leslie Smith,3,Male,001-878-644-4344x49919,Retina,2007-01-29,Dr.B,Eye Hospital
126,127,Tracy Willis,26,Male,(267)476-4307,Glaucoma,1981-03-17,Dr.A,Eye Hospital
127,128,Michelle Gonzalez,27,Male,(290)515-0158x4655,Diabetes,1986-04-01,Dr.C,Eye Hospital
128,129,Philip Ballard,21,Male,5182913773,Glaucoma,2002-02-08,Dr.B,Eye Hospital
129,130,Crystal Michael,79,Female,2402111374,Normal,1988-09-16,Dr.B,Eye Hospital
130,131,Lori Dawson,45,Male,702.544.5738,Glaucoma,1994-07-21,Dr.B,Eye Hospital
131,132,Kelly Lee,67,Male,001-725-925-4230x07353,Cataract,2005-06-09,Dr.B,Eye Hospital
132,133,Claudia Hernandez,38,Male,001-206-495-4491x520,Normal,2016-06-13,Dr.C,Eye Hospital
133,134,Joseph Hanson,58,Male,694.916.9681,Normal,1984-07-07,Dr.C,Eye Hospital
134,135,Michael Arias,3,Female,322-726-7200x89255,Cataract,2017-01-04,Dr.A,Eye Hospital
135,136,Anita Thomas,44,Female,381.855.5387x948,Diabetes,1999-07-26,Dr.C,Eye Hospital
136,137,Zachary Lewis,45,Male,784.904.9613,Normal,1983-06-12,Dr.A,Eye Hospital
137,138,Mr. Devin Peterson,19,Female,(618)985-7367x7192,Retina,1972-02-19,Dr.C,Eye Hospital
138,139,Kathy Harrell,72,Female,873.697.6398x32515,Cataract,1988-01-10,Dr.C,Eye Hospital
139,140,Rachel Martin,53,Male,(405)905-5805x3735,Cataract,2019-03-04,Dr.B,Eye Hospital
140,141,Michael Andrews,42,Female,537-500-3399,Retina,1971-03-14,Dr.A,Eye Hospital
141,142,Maria Jacobson,19,Male,773.528.3863,Cataract,2005-01-10,Dr.A,Eye Hospital
142,143,Ashley Wood,71,Male,(343)556-8218x85291,Normal,1978-04-20,Dr.C,Eye Hospital
143,144,Alice Jacobs MD,21,Female,(734)551-7571,Retina,2022-04-29,Dr.A,Eye Hospital
144,145,Karen Rojas MD,32,Female,703-976-6376x489,Normal,2003-09-16,Dr.B,Eye Hospital
145,146,Beth Walker,36,Female,(871)956-0584,Cataract,1977-08-01,Dr.C,Eye Hospital
146,147,Justin Rojas,40,Female,001-686-565-8572,Retina,2000-07-17,Dr.A,Eye Hospital
147,148,Michael Robinson,19,Female,(564)383-1844,Glaucoma,2021-06-12,Dr.A,Eye Hospital
148,149,Kathleen Sosa,43,Male,613-896-2618,Cataract,2019-03-18,Dr.A,Eye Hospital
149,150,Victor Cross,28,Male,8785302331,Cataract,2009-06-22,Dr.C,Eye Hospital
150,151,Felicia Evans,39,Female,868.371.9818x6258,Retina,1994-10-01,Dr.A,Eye Hospital
151,152,Jaime Mays,63,Male,(822)714-6832x2264,Glaucoma,1993-08-20,Dr.A,Eye Hospital
152,153,Rhonda Vincent,10,Male,973-412-9743,Retina,1989-08-09,Dr.A,Eye Hospital
153,154,Rachel Gonzalez,19,Female,229.821.4150,Retina,2006-05-12,Dr.B,Eye Hospital
154,155,Leroy Nunez,4,Female,297.537.1301x81642,Glaucoma,2006-12-14,Dr.B,Eye Hospital
155,156,David Preston,10,Female,(788)633-4460,Diabetes,1976-06-19,Dr.B,Eye Hospital
156,157,Timothy Ford,47,Female,814-385-7992x2401,Cataract,2006-11-28,Dr.B,Eye Hospital
157,158,Kayla Davenport,48,Male,622-683-4352x2896,Retina,2020-10-21,Dr.C,Eye Hospital
158,159,David Johnson,47,Female,001-591-514-7852x030,Cataract,1980-12-05,Dr.B,Eye Hospital
159,160,Natalie Carpenter,53,Male,(374)435-1643,Cataract,1980-04-10,Dr.A,Eye Hospital
160,161,Jennifer Gomez,28,Female,+1-504-553-3519x08858,Retina,1981-12-20,Dr.B,Eye Hospital
161,162,Cameron Wilson,69,Female,+1-318-522-3433x3019,Cataract,2004-11-30,Dr.B,Eye Hospital
162,163,John Miller,51,Female,(855)386-5795x50161,Retina,1976-05-21,Dr.B,Eye Hospital
163,164,Brittany Ellis,38,Male,+1-916-635-3421,Retina,2012-03-23,Dr.A,Eye Hospital
164,165,Mary Lopez,8,Female,273-773-8361x4353,Diabetes,2010-12-10,Dr.A,Eye Hospital
165,166,Edward Smith,7,Male,001-503-492-0155x7446,Normal,2013-03-01,Dr.C,Eye Hospital
166,167,Joy Green,5,Male,940-924-9451x4508,Retina,2019-11-26,Dr.B,Eye Hospital
167,168,Gary Farrell,75,Male,252.214.1203,Cataract,2006-03-19,Dr.B,Eye Hospital
168,169,Brenda Arias,4,Female,934-287-0878,Glaucoma,1996-03-24,Dr.C,Eye Hospital
169,170,Paul Trevino,34,Female,(309)325-9722x1431,Normal,1986-06-06,Dr.C,Eye Hospital
170,171,Christopher Alexander,36,Female,968.800.5352x616,Normal,2016-12-06,Dr.C,Eye Hospital
171,172,Heather Castaneda,56,Male,001-663-870-7061x48277,Normal,2023-02-15,Dr.A,Eye Hospital
172,173,Ronald Jones,57,Male,(278)914-1214x053,Retina,1988-09-06,Dr.A,Eye Hospital
173,174,Robert Thomas,33,Female,001-246-642-0487x94448,Glaucoma,1971-11-26,Dr.C,Eye Hospital
174,175,Kaitlyn Warren,31,Female,001-492-890-4595x217,Cataract,1997-03-12,Dr.B,Eye Hospital
175,176,Christopher Mills,13,Female,+1-396-354-5007x90033,Normal,2019-06-10,Dr.B,Eye Hospital
176,177,Jill Turner,17,Male,8528765700,Glaucoma,2016-10-31,Dr.A,Eye Hospital
177,178,Ryan Phillips,40,Male,+1-378-370-6372x250,Retina,1974-11-05,Dr.A,Eye Hospital
178,179,Melissa Hall,42,Female,327-626-0265x744,Diabetes,1972-04-28,Dr.B,Eye Hospital
179,180,Victoria Smith,65,Female,+1-667-669-6275x220,Glaucoma,1983-10-16,Dr.B,Eye Hospital
180,181,Meagan Brown,70,Female,(555)244-0325,Retina,2021-06-06,Dr.C,Eye Hospital
181,182,Aaron Wolf,35,Female,925-394-5267x8407,Normal,1997-01-05,Dr.C,Eye Hospital
182,183,Amanda Keller,78,Female,672.253.0014,Retina,1978-03-11,Dr.C,Eye Hospital
183,184,Garrett Hood,71,Male,001-495-825-8125x6803,Glaucoma,2022-07-13,Dr.C,Eye Hospital
184,185,Nathan Garcia,23,Male,745.499.4991,Retina,2015-04-26,Dr.B,Eye Hospital
185,186,Carrie Jordan,73,Female,001-998-962-0435x70317,Cataract,1993-12-27,Dr.B,Eye Hospital
186,187,Samuel Lynch,12,Male,(632)840-6134,Retina,2023-05-13,Dr.B,Eye Hospital
187,188,Lisa Neal,39,Male,(774)212-8082x96069,Glaucoma,1991-06-09,Dr.B,Eye Hospital
188,189,April Matthews,74,Male,+1-701-868-7945,Diabetes,2022-10-18,Dr.A,Eye Hospital
189,190,Brittany Castro,22,Female,+1-369-647-1222,Diabetes,2017-01-10,Dr.C,Eye Hospital
190,191,Bradley Cisneros,56,Female,771-571-1036,Diabetes,1987-11-14,Dr.B,Eye Hospital
191,192,Alexander Lawrence,33,Male,346-266-2458,Diabetes,2020-06-23,Dr.C,Eye Hospital
192,193,Joshua Spears,23,Male,482-782-2823,Cataract,2004-04-18,Dr.A,Eye Hospital
193,194,Jonathan George,34,Female,938.208.7996x932,Retina,1973-07-25,Dr.C,Eye Hospital
194,195,Robert Shelton,52,Female,(767)965-0272,Cataract,2020-06-15,Dr.A,Eye Hospital
195,196,Alison Gardner,78,Male,+1-972-594-2940,Normal,1991-08-28,Dr.B,Eye Hospital
196,197,Beverly Bradford,79,Female,+1-767-481-8348x365,Normal,1987-10-11,Dr.C,Eye Hospital
197,198,Frederick Nguyen,44,Male,(772)740-0165,Diabetes,2014-12-14,Dr.A,Eye Hospital
198,199,Stephen Riley,35,Male,001-933-970-1685x68542,Glaucoma,1988-06-15,Dr.C,Eye Hospital
199,200,Steven Wilkerson,32,Male,3505813640,Diabetes,1998-03-22,Dr.A,Eye Hospital
200,201,Joshua Horn,60,Male,902-231-6451x45938,Retina,1978-11-05,Dr.A,Eye Hospital
201,202,Darin Walker,41,Female,(205)240-6535,Glaucoma,2014-02-13,Dr.B,Eye Hospital
202,203,Kayla Rodriguez,31,Female,(771)712-0327,Glaucoma,2000-05-31,Dr.B,Eye Hospital
203,204,Mrs. Stephanie Garza,14,Male,2715860899,Glaucoma,1983-10-15,Dr.B,Eye Hospital
204,205,Chelsea Warren,17,Female,4383741314,Glaucoma,2002-04-01,Dr.B,Eye Hospital
205,206,Wayne Jones,70,Male,232.258.4101x553,Normal,1996-10-24,Dr.A,Eye Hospital
206,207,Eric Miller,8,Male,001-366-767-1446,Diabetes,1972-04-17,Dr.B,Eye Hospital
207,208,Jennifer Watkins,64,Female,750.748.3850x29296,Glaucoma,1988-03-19,Dr.C,Eye Hospital
208,209,Bradley Lopez,47,Male,001-858-788-6314x5566,Cataract,2000-01-13,Dr.C,Eye Hospital
209,210,Virginia Lewis,37,Female,001-552-567-1144x41499,Glaucoma,1996-09-13,Dr.A,Eye Hospital
210,211,Mrs. Jeanette Fitzpatrick,41,Male,+1-237-685-0496x44152,Cataract,1970-03-22,Dr.A,Eye Hospital
211,212,Lauren Robertson,15,Female,681.277.7480,Cataract,1971-10-06,Dr.A,Eye Hospital
212,213,Rhonda Morgan,74,Female,740.811.3766,Glaucoma,1990-08-26,Dr.B,Eye Hospital
213,214,Michael Wood,20,Male,847-321-0501x3749,Cataract,1991-03-18,Dr.B,Eye Hospital
214,215,Randall Vargas,18,Male,001-462-955-1176x486,Diabetes,2021-08-28,Dr.C,Eye Hospital
215,216,Alexandra Mccarthy,63,Male,311.215.3508,Glaucoma,1987-05-12,Dr.A,Eye Hospital
216,217,Mrs. Melanie Simmons,78,Male,891.319.5450x5172,Glaucoma,2000-05-27,Dr.A,Eye Hospital
217,218,Amy Le DDS,43,Female,(773)695-0796,Diabetes,2024-01-29,Dr.C,Eye Hospital
218,219,Mr. David Phillips DDS,55,Female,+1-479-752-6924x4138,Glaucoma,2026-02-12,Dr.C,Eye Hospital
219,220,Mary Oconnell,69,Female,+1-623-738-4430x45290,Glaucoma,1995-08-10,Dr.A,Eye Hospital
220,221,Katherine Davila,31,Female,414.572.1060x74851,Normal,1995-07-27,Dr.C,Eye Hospital
221,222,Mr. Nathaniel Perez Jr.,22,Female,504.996.8130x9901,Retina,1998-12-16,Dr.A,Eye Hospital
222,223,Ryan Daniels,78,Female,(602)587-4460,Glaucoma,1994-04-08,Dr.B,Eye Hospital
223,224,Aaron Sullivan,58,Female,+1-256-312-3509x80313,Normal,2007-12-27,Dr.A,Eye Hospital
224,225,Robert Wilson,77,Male,+1-546-219-1312x83631,Cataract,1976-04-20,Dr.C,Eye Hospital
225,226,Travis Woods,57,Male,+1-933-786-9789x1611,Glaucoma,2015-12-24,Dr.C,Eye Hospital
226,227,Jacob White,26,Female,+1-638-744-8382x0874,Retina,2006-11-14,Dr.B,Eye Hospital
227,228,James Elliott,48,Male,(661)612-1686,Glaucoma,2013-12-28,Dr.C,Eye Hospital
228,229,Carolyn Reeves,44,Female,735.422.6425x9036,Normal,1992-08-27,Dr.B,Eye Hospital
229,230,Jason Garrett,17,Male,482-382-3448x583,Glaucoma,2007-11-12,Dr.B,Eye Hospital
230,231,Steven Case,28,Female,(318)483-6447x3067,Diabetes,1973-09-30,Dr.A,Eye Hospital
231,232,Teresa Hicks,64,Male,+1-742-772-0641x585,Diabetes,2025-03-02,Dr.C,Eye Hospital
232,233,Joshua Green,72,Female,001-266-728-2524x67101,Diabetes,1990-01-03,Dr.B,Eye Hospital
233,234,Antonio Rush,26,Male,(774)440-5173x700,Normal,2019-07-15,Dr.A,Eye Hospital

In [16]:
camp_data = []

for i in range(500):
    camp_data.append({
        "Camp_ID": i+1,
        "Name": fake.name(),
        "Age": random.randint(1,80),
        "Gender": random.choice(["Male","Female"]),
        "Village": fake.city(),
        "Screening_Result": random.choice(["Normal","Cataract","Refer Hospital"]),
        "Camp_Date": fake.date(),
        "Doctor": random.choice(["Dr.A","Dr.B","Dr.C"])
    })

camp_df = pd.DataFrame(camp_data)

camp_df.to_excel("camp_data.xlsx", index=False)

print("Camp Data Generated")
camp_df.head()

Camp Data Generated

,Camp_ID,Name,Age,Gender,Village,Screening_Result,Camp_Date,Doctor
0,1,Rebekah Davis,62,Male,Barbarachester,Normal,1971-02-22,Dr.B
1,2,Hannah Meyer,80,Male,Melissaland,Cataract,2012-06-11,Dr.B
2,3,Francis Compton,43,Male,Justinchester,Normal,1990-06-13,Dr.B
3,4,Amy Roberts,4,Female,New Jennyville,Refer Hospital,1980-12-10,Dr.B
4,5,Julie Clark,20,Female,Andrewbury,Cataract,1980-12-27,Dr.A

In [17]:
pd.set_option('display.max_rows', 500)
camp_df

,Camp_ID,Name,Age,Gender,Village,Screening_Result,Camp_Date,Doctor
0,1,Rebekah Davis,62,Male,Barbarachester,Normal,1971-02-22,Dr.B
1,2,Hannah Meyer,80,Male,Melissaland,Cataract,2012-06-11,Dr.B
2,3,Francis Compton,43,Male,Justinchester,Normal,1990-06-13,Dr.B
3,4,Amy Roberts,4,Female,New Jennyville,Refer Hospital,1980-12-10,Dr.B
4,5,Julie Clark,20,Female,Andrewbury,Cataract,1980-12-27,Dr.A
5,6,Jordan Martinez,11,Male,East Derrick,Refer Hospital,1976-01-28,Dr.A
6,7,Sue Hall,47,Female,Howardburgh,Refer Hospital,2002-07-16,Dr.C
7,8,David Braun,75,Male,North Sharon,Refer Hospital,1993-06-06,Dr.A
8,9,Lauren Matthews,16,Male,Lawrencechester,Refer Hospital,1994-11-17,Dr.B
9,10,Kathy Mitchell,64,Female,Sergioberg,Normal,1980-04-03,Dr.B
10,11,Brittney Meadows,37,Female,Lawsonmouth,Cataract,2025-04-03,Dr.A
11,12,Robert Walker,76,Female,East Angelafurt,Normal,2016-05-12,Dr.C
12,13,Steven Walker,57,Female,Clarkland,Normal,1989-09-06,Dr.A
13,14,Sarah Baker,66,Male,North Rickyshire,Cataract,2022-08-20,Dr.A
14,15,Cory Kennedy,6,Male,Taylorview,Cataract,1972-01-13,Dr.B
15,16,Allison Spencer,57,Female,Benjaminfurt,Cataract,2011-08-05,Dr.C
16,17,Kara Koch,1,Female,West Lauraport,Cataract,1970-01-03,Dr.B
17,18,James Sutton,43,Male,West Emma,Normal,2017-07-16,Dr.A
18,19,Mr. David Hamilton,20,Male,Hernandezborough,Cataract,2025-11-30,Dr.B
19,20,Justin Brown,11,Female,New Allison,Refer Hospital,1994-07-21,Dr.B
20,21,Julia Jacobson,54,Male,Bradleyfurt,Refer Hospital,1980-02-14,Dr.A
21,22,Chad Conway,58,Female,North Craigton,Cataract,2012-07-16,Dr.A
22,23,Christian Burnett DDS,12,Male,North Jimmyhaven,Normal,2022-06-28,Dr.C
23,24,Rhonda Wallace,11,Female,Lake Bonnie,Normal,2003-01-14,Dr.A
24,25,Katie Ford,6,Female,East Eric,Refer Hospital,2003-12-01,Dr.B
25,26,Adam Dillon,46,Male,North David,Refer Hospital,1994-08-11,Dr.A
26,27,Meghan Gomez,67,Male,New Lydiahaven,Refer Hospital,2013-10-04,Dr.A
27,28,Matthew Lopez,25,Female,Port Chelsealand,Refer Hospital,1992-06-26,Dr.B
28,29,Matthew Davis,26,Male,East Maria,Normal,1989-11-05,Dr.A
29,30,Eric Jackson,50,Female,Jonesport,Normal,1972-01-25,Dr.A
30,31,Michael Murray,46,Female,North Darrellborough,Normal,1992-08-16,Dr.C
31,32,Dawn Henry,1,Female,Lake Kevinton,Normal,2018-11-14,Dr.B
32,33,Jeremy Black,14,Female,Port Christopher,Normal,1977-08-09,Dr.A
33,34,Alejandra Shelton,38,Female,Richardsonchester,Refer Hospital,1985-12-23,Dr.B
34,35,Monica Mckinney,39,Female,Millerhaven,Cataract,2016-02-07,Dr.C
35,36,Kirsten Harris,45,Male,South Haley,Normal,1976-04-07,Dr.C
36,37,Cassie Herrera,24,Female,Oconnorfort,Normal,1985-06-14,Dr.B
37,38,Dwayne Reed,63,Male,East Abigail,Refer Hospital,2017-07-12,Dr.B
38,39,Cassandra Hooper,23,Male,Tinaport,Refer Hospital,2002-12-08,Dr.B
39,40,Theresa Ortega,3,Male,Amyville,Cataract,2006-10-06,Dr.A
40,41,Michael Anderson,40,Male,South Edwardshire,Refer Hospital,1974-12-14,Dr.C
41,42,Casey Jones,11,Male,New Ryan,Cataract,1975-07-10,Dr.B
42,43,Sandra Casey,31,Male,Bernardland,Normal,2012-07-25,Dr.C
43,44,Michael Bradley,35,Female,Thomasborough,Normal,2014-01-26,Dr.C
44,45,Amber Cruz,4,Male,South Christopher,Normal,2018-05-12,Dr.A
45,46,Elizabeth Flores,79,Female,Amandachester,Cataract,1989-09-09,Dr.C
46,47,Jack Flynn,43,Male,Annebury,Normal,2022-01-14,Dr.B
47,48,Dana Fowler,76,Female,North Christina,Refer Hospital,2024-04-28,Dr.C
48,49,Madison Jordan,48,Male,North Catherine,Normal,2001-08-06,Dr.C
49,50,Tammy Martin,38,Male,Moodyshire,Normal,1996-12-23,Dr.C
50,51,Angelica Lynch,80,Male,Lake Brianfort,Cataract,2001-07-02,Dr.A
51,52,Lisa Griffith,10,Male,Susanton,Refer Hospital,1997-10-28,Dr.B
52,53,Natasha Smith,36,Male,New Jesus,Cataract,2006-04-29,Dr.A
53,54,Matthew Cordova,69,Female,Romanfort,Normal,1994-08-08,Dr.A
54,55,Melvin Torres,69,Female,Howardton,Cataract,1981-07-20,Dr.C
55,56,Charlotte Good,24,Male,Port Jill,Normal,2020-09-19,Dr.B
56,57,Larry Mann,76,Male,Port Kimberly,Refer Hospital,1973-03-16,Dr.B
57,58,Timothy Palmer,74,Female,North Sandra,Refer Hospital,2006-05-22,Dr.C
58,59,Emily Odom DVM,4,Male,Sarahville,Normal,2017-07-18,Dr.C
59,60,Garrett Odonnell,52,Male,New Nathan,Refer Hospital,2000-05-21,Dr.C
60,61,Vincent Howard,23,Female,Benjaminmouth,Cataract,1988-04-20,Dr.B
61,62,Christopher Bradford,20,Female,Port Ryan,Cataract,2025-05-09,Dr.B
62,63,William Reyes,21,Female,Ronaldport,Cataract,1987-09-15,Dr.A
63,64,Gina Jackson,80,Female,New Jennifer,Cataract,2024-04-21,Dr.C
64,65,Leah Landry,42,Female,North Holly,Cataract,1982-10-23,Dr.A
65,66,Jennifer Mosley,67,Female,Lake Anthonytown,Refer Hospital,1986-09-12,Dr.A
66,67,Stephen Smith,12,Male,East Julie,Cataract,2009-05-04,Dr.C
67,68,Matthew Murray,24,Male,North Saraside,Cataract,1983-08-17,Dr.B
68,69,Michael Bailey,46,Male,East Melissamouth,Refer Hospital,2009-03-09,Dr.B
69,70,Patricia Pitts,77,Male,Schroederview,Cataract,2002-08-02,Dr.B
70,71,Tracy Tran,2,Male,Nancytown,Cataract,2024-09-16,Dr.B
71,72,Susan Simmons,16,Male,Port Michelleview,Refer Hospital,2014-07-09,Dr.B
72,73,Samantha York,46,Male,Markborough,Refer Hospital,2022-11-28,Dr.B
73,74,Robin Bradley,39,Female,New Mark,Normal,2005-03-29,Dr.A
74,75,Dana Gallegos,69,Male,South Kimberlyfurt,Normal,2004-01-21,Dr.B
75,76,Vanessa Long,31,Female,Lake Stacy,Normal,1976-05-30,Dr.C
76,77,Logan Holland,69,Male,Wilsonville,Cataract,1970-11-23,Dr.B
77,78,Christina Sanders,71,Female,Bakerburgh,Refer Hospital,2017-03-11,Dr.A
78,79,Rodney Gutierrez,14,Female,Monicahaven,Refer Hospital,1979-02-20,Dr.A
79,80,Carrie Hall,14,Female,Port Kelly,Refer Hospital,2013-03-06,Dr.A
80,81,Mark Castro,37,Female,Cynthiatown,Normal,1983-11-27,Dr.C
81,82,Jennifer Collins,54,Female,Watkinsville,Refer Hospital,2023-04-17,Dr.C
82,83,Rachel Mckinney,57,Male,Catherinechester,Normal,1977-03-20,Dr.A
83,84,Jose Butler,5,Male,Ericmouth,Cataract,1970-03-02,Dr.A
84,85,Diana Hudson,34,Female,Bautistatown,Normal,1991-02-04,Dr.B
85,86,Maria Howard,55,Male,North Kathleenbury,Cataract,1980-01-26,Dr.B
86,87,John Huynh,15,Female,Lake Samuelberg,Cataract,2010-05-04,Dr.A
87,88,Robert Reid,16,Female,Lake Andrew,Normal,2011-08-06,Dr.C
88,89,Alexander Maddox,34,Male,West Toddborough,Cataract,1993-09-27,Dr.C
89,90,Brian Tucker,32,Female,Smithville,Refer Hospital,2008-08-28,Dr.A
90,91,Zachary Meyer,13,Female,Whiteport,Normal,1979-03-12,Dr.B
91,92,Matthew Molina,51,Female,East Ricardoside,Normal,2024-03-14,Dr.A
92,93,Julian Kelly,37,Female,Keithhaven,Cataract,2008-03-11,Dr.C
93,94,Jill Martinez,44,Female,Sandraberg,Normal,2010-01-04,Dr.B
94,95,James Edwards,79,Female,Port Stacyview,Normal,2018-06-26,Dr.B
95,96,Linda Shields,80,Female,Morsebury,Cataract,1995-09-26,Dr.B
96,97,Laurie Ortiz,39,Female,Alvinberg,Normal,2017-09-19,Dr.A
97,98,John Martin,30,Male,South Lauraville,Normal,2008-06-01,Dr.B
98,99,Jennifer Caldwell,1,Female,New Mark,Normal,1977-02-15,Dr.A
99,100,Christine Thomas,47,Male,Jonesside,Normal,2015-10-25,Dr.C
100,101,John Bruce,63,Male,North William,Normal,1977-09-21,Dr.A
101,102,Michelle Morrow,19,Female,Lake Joseph,Cataract,2010-01-17,Dr.C
102,103,Dr. Keith Evans,33,Male,Port Aliciastad,Normal,2000-03-10,Dr.C
103,104,Julie Hart,25,Female,Youngburgh,Cataract,1973-04-24,Dr.C
104,105,Lauren Hoover,67,Male,East Melissaville,Refer Hospital,1983-08-05,Dr.C
105,106,John Collins,63,Male,Port Elainefurt,Normal,1977-05-14,Dr.A
106,107,Andrew Owen,64,Male,Lake Ruben,Refer Hospital,1995-11-01,Dr.A
107,108,Matthew Miller,13,Female,Hamiltonhaven,Normal,2001-12-20,Dr.C
108,109,Thomas Rodriguez,29,Female,East Brandon,Cataract,2004-02-12,Dr.C
109,110,Adam Rogers,43,Male,Villanuevamouth,Normal,2007-10-07,Dr.C
110,111,Patricia Evans,8,Male,New Marktown,Refer Hospital,2021-12-01,Dr.A
111,112,Jacob Adams,52,Male,New Jasonbury,Normal,1994-06-24,Dr.C
112,113,Ian Ross,5,Female,North Marybury,Refer Hospital,1988-09-15,Dr.C
113,114,Nicholas Mann,67,Male,Lake Michaelmouth,Cataract,2006-04-03,Dr.A
114,115,Bridget Pacheco,2,Female,East Danieltown,Refer Hospital,2017-11-13,Dr.C
115,116,Robert Yates,49,Male,Ryanbury,Refer Hospital,1998-11-27,Dr.A
116,117,Victoria Harding,70,Female,East Ryanhaven,Normal,1994-05-18,Dr.C
117,118,Austin Chaney,5,Male,New Ginamouth,Normal,1992-11-07,Dr.C
118,119,Albert James,22,Female,Danielstad,Refer Hospital,2015-05-29,Dr.B
119,120,Samuel Daniel,56,Female,Lisatown,Normal,2021-02-06,Dr.C
120,121,Susan Adams,73,Male,South Christopher,Refer Hospital,1976-12-08,Dr.A
121,122,Marc King,13,Female,New Gwendolyn,Refer Hospital,2000-05-09,Dr.B
122,123,Katie Valenzuela,79,Female,East Brenda,Refer Hospital,2022-01-14,Dr.A
123,124,Kaylee Boyd,26,Female,Danielport,Cataract,2016-11-03,Dr.C
124,125,Charles Daniels,69,Male,Lake Keith,Normal,1996-05-22,Dr.B
125,126,Mary Johnston,24,Female,Andreaport,Cataract,2016-05-09,Dr.A
126,127,Dwayne Schmidt,52,Female,Blacktown,Refer Hospital,2019-08-03,Dr.A
127,128,Kristin Mcdonald,2,Female,North Melissastad,Cataract,1973-05-13,Dr.B
128,129,Debra Burke DDS,52,Male,North Shawnshire,Refer Hospital,2009-01-07,Dr.C
129,130,Adrienne Thompson,52,Female,Leeview,Normal,2015-06-02,Dr.B
130,131,Monica Collins,26,Female,Matthewborough,Cataract,1975-09-17,Dr.B
131,132,Nicholas Brown,63,Male,East Kenneth,Cataract,2004-06-06,Dr.C
132,133,Lisa Murillo,79,Female,North Rachel,Normal,2025-09-22,Dr.A
133,134,Christopher Lee,5,Male,Robleston,Cataract,1993-05-07,Dr.B
134,135,Jeffrey Clark,34,Male,South Julia,Normal,2008-12-15,Dr.B
135,136,Kevin Mason,74,Female,Port Robertmouth,Refer Hospital,2024-08-10,Dr.B
136,137,Jermaine Jones,33,Female,Stanleyfurt,Refer Hospital,1972-09-13,Dr.B
137,138,Emily Cox,56,Female,New Ashleymouth,Normal,2017-07-24,Dr.A
138,139,Catherine Moore,59,Male,South Timothyberg,Refer Hospital,2016-08-13,Dr.B
139,140,Susan Payne,14,Male,Toddport,Cataract,2021-06-21,Dr.A
140,141,Aaron Chavez,37,Female,Olsonview,Normal,1987-01-09,Dr.C
141,142,Michael Lee,66,Male,Spencerport,Cataract,2020-05-23,Dr.A
142,143,Carrie Williams,33,Male,West Natalie,Cataract,2002-11-24,Dr.A
143,144,Lisa Hogan,29,Male,East Brian,Cataract,2013-10-30,Dr.A
144,145,Lauren Jones,45,Male,Solomonbury,Cataract,2024-10-04,Dr.B
145,146,Chelsea Hall,38,Male,Johnmouth,Refer Hospital,1997-11-27,Dr.B
146,147,Hannah Sanchez,46,Male,West Elizabeth,Cataract,2023-01-30,Dr.A
147,148,Brenda Orozco,62,Female,Hendricksfurt,Refer Hospital,1996-04-23,Dr.A
148,149,Lisa Roach,57,Female,Delgadoview,Normal,1970-10-18,Dr.A
149,150,Kyle Bailey,71,Male,Greenmouth,Cataract,1975-02-20,Dr.C
150,151,Billy Davis,7,Male,Andrewberg,Cataract,2003-10-04,Dr.C
151,152,Thomas Wilkerson,54,Female,Evansfort,Refer Hospital,2018-06-18,Dr.A
152,153,Patricia Marks,18,Male,East Leehaven,Cataract,2009-10-29,Dr.A
153,154,Warren Davis,52,Female,Lake Heidi,Refer Hospital,1989-12-17,Dr.B
154,155,Terry Barber,5,Female,Lake Jamesview,Refer Hospital,2016-08-12,Dr.C
155,156,Jacob Gutierrez,71,Female,Jamesborough,Cataract,1977-08-28,Dr.C
156,157,Charles Tucker,39,Male,Harrisonside,Normal,2019-10-28,Dr.C
157,158,Christine Hunter,71,Male,New Jessica,Cataract,2002-12-30,Dr.B
158,159,Rhonda Cummings,13,Male,North Tina,Cataract,1993-04-12,Dr.B
159,160,Amber Moore,57,Male,West Chelsea,Cataract,2006-10-31,Dr.B
160,161,Michelle Mendoza,19,Female,Melissaview,Cataract,1971-11-17,Dr.A
161,162,Heather Bird,76,Female,Brownburgh,Cataract,1992-08-04,Dr.B
162,163,Katrina Holmes,22,Female,New Jennahaven,Refer Hospital,2016-06-17,Dr.C
163,164,Jack Leblanc,50,Female,Lindastad,Refer Hospital,2005-06-20,Dr.B
164,165,Rebecca Keller,80,Female,Lake Juan,Cataract,1974-10-19,Dr.A
165,166,Angela Huffman,43,Male,Port Margaret,Normal,2012-11-15,Dr.C
166,167,Barbara Pugh,68,Male,Jordanfort,Refer Hospital,2010-04-13,Dr.B
167,168,Michael Hanson,4,Male,North Stephanie,Normal,1996-08-07,Dr.C
168,169,Derek Hill,64,Male,Smithton,Normal,2014-01-05,Dr.C
169,170,Brian Edwards,34,Male,South Sabrinaville,Refer Hospital,2021-11-25,Dr.C
170,171,Renee Jordan,46,Male,Aprilport,Refer Hospital,1992-02-21,Dr.B
171,172,Jesse Green,66,Male,Alyssahaven,Refer Hospital,2010-07-03,Dr.A
172,173,Kimberly Smith,75,Male,Harrisport,Cataract,1996-05-08,Dr.C
173,174,Tyrone Green,44,Female,Jonesview,Refer Hospital,1999-07-31,Dr.A
174,175,Ebony Kemp,61,Male,Andreamouth,Cataract,1983-05-19,Dr.A
175,176,Jessica Charles,12,Male,Lake Holly,Cataract,2019-12-15,Dr.A
176,177,Kristin Rodriguez,79,Male,Connieport,Refer Hospital,2021-06-06,Dr.A
177,178,Haley Turner,53,Female,Greenland,Normal,1997-05-19,Dr.C
178,179,Erin Walter,28,Female,Marshallburgh,Cataract,1982-05-23,Dr.B
179,180,Shelly Lawson,57,Male,New Todd,Refer Hospital,1990-01-24,Dr.B
180,181,Becky Mccullough,43,Male,Hollymouth,Normal,2017-10-23,Dr.A
181,182,Brian Mejia,8,Female,Lake Andrewshire,Normal,2010-03-15,Dr.C
182,183,Tracy Terry,9,Female,West Michael,Normal,1979-08-21,Dr.C
183,184,Adam Townsend,1,Female,Joshuaberg,Normal,2019-09-14,Dr.A
184,185,Vanessa Jones,13,Female,East Matthewmouth,Normal,2011-10-11,Dr.B
185,186,Deborah Douglas,10,Male,North Aprilbury,Cataract,2005-09-02,Dr.A
186,187,Kathleen Wright,53,Male,Nunezside,Normal,1991-12-02,Dr.C
187,188,Cheryl Hicks,79,Male,Cynthiaville,Normal,1976-03-07,Dr.B
188,189,Jennifer Wong,46,Male,Jakeshire,Cataract,2011-07-25,Dr.B
189,190,Glenn Kirby,59,Female,Madisonstad,Refer Hospital,1974-08-21,Dr.B
190,191,Donna Thompson,15,Male,Lake Stephen,Refer Hospital,1999-09-27,Dr.A
191,192,Grace Porter,76,Female,Port Douglas,Refer Hospital,2024-02-28,Dr.A
192,193,Tamara Conway,54,Female,Matthewfurt,Refer Hospital,1971-06-26,Dr.B
193,194,Lisa Byrd,80,Male,Michaelfurt,Refer Hospital,1971-06-02,Dr.B
194,195,Sarah Schultz,61,Female,Lake Stevenbury,Refer Hospital,2015-12-18,Dr.A
195,196,Amy Cooper,8,Female,Greenefort,Refer Hospital,1998-03-19,Dr.B
196,197,Jon Griffin,48,Female,South Brittany,Cataract,2003-10-31,Dr.B
197,198,Mr. Matthew Torres,42,Male,South Carolville,Normal,1973-06-17,Dr.A
198,199,Michael Ortiz,41,Female,South Shirley,Cataract,1987-03-03,Dr.B
199,200,Debbie Jones,3,Female,West Michael,Normal,1986-06-03,Dr.B
200,201,Caroline Weaver,25,Male,Lake Drewport,Cataract,2013-01-30,Dr.C
201,202,Holly Velasquez,44,Female,Lake Brian,Refer Hospital,2008-09-21,Dr.B
202,203,Ryan Nelson,16,Male,Reesebury,Refer Hospital,2017-02-28,Dr.C
203,204,Shawn Clarke,65,Female,North Michael,Cataract,1999-10-10,Dr.B
204,205,Tom Gutierrez,25,Female,South Jennifermouth,Normal,2022-03-27,Dr.A
205,206,Sabrina Larsen,36,Male,Jodiville,Refer Hospital,1998-10-09,Dr.B
206,207,Cynthia Anderson,39,Female,Amandatown,Normal,2017-02-28,Dr.B
207,208,Melissa Jefferson MD,37,Male,South Michael,Refer Hospital,1973-11-23,Dr.C
208,209,Mark Martin,25,Male,Yolandaton,Normal,1979-12-03,Dr.B
209,210,John Rodriguez,55,Male,Port Kaylachester,Cataract,2005-01-28,Dr.A
210,211,Rachel Vega,33,Female,Myersville,Cataract,1988-03-08,Dr.A
211,212,Mariah Thompson,61,Female,South Lindsey,Refer Hospital,1995-07-29,Dr.C
212,213,Andrew Grant,31,Male,Stewartberg,Cataract,1996-06-28,Dr.B
213,214,Mr. Joseph Young,31,Female,Raymouth,Normal,1972-12-31,Dr.A
214,215,Breanna Burgess,52,Female,West Patrickmouth,Normal,1995-04-13,Dr.B
215,216,Luis Curry,80,Female,New Rebecca,Refer Hospital,2013-12-11,Dr.A
216,217,Antonio Fuentes,42,Female,New Scott,Cataract,1985-01-01,Dr.B
217,218,Charles Owens,53,Male,West Virginia,Refer Hospital,2001-12-27,Dr.C
218,219,Kim Warren,52,Male,East Valeriemouth,Refer Hospital,1976-09-07,Dr.C
219,220,Regina Sanchez,31,Female,South Geneport,Cataract,1981-10-16,Dr.C
220,221,Eugene Jones,51,Female,Burkestad,Cataract,1978-12-28,Dr.C
221,222,Cody Owen,20,Male,Watkinstown,Normal,1976-07-31,Dr.A
222,223,Erik Weaver,61,Female,Brandonborough,Cataract,1990-06-04,Dr.B
223,224,Dakota Mueller,26,Female,Gonzaleschester,Refer Hospital,1980-08-27,Dr.B
224,225,John Garcia,80,Female,Steinstad,Refer Hospital,2013-11-02,Dr.B
225,226,Lindsey Booker,30,Female,Wilsonview,Refer Hospital,1974-04-17,Dr.C
226,227,Katelyn Beck,39,Female,Michaelfort,Refer Hospital,2020-07-26,Dr.A
227,228,Jacob Bailey,39,Male,Lake Nancy,Normal,1971-07-26,Dr.C
228,229,John Montes,38,Female,South Jason,Cataract,1975-02-11,Dr.A
229,230,Gail Lopez,6,Male,West Jaclynburgh,Cataract,1977-06-10,Dr.A
230,231,Francisco Peterson,19,Male,East William,Cataract,1985-06-02,Dr.C
231,232,Joseph Andrews,7,Male,Barrytown,Cataract,1979-03-30,Dr.B
232,233,Jesse Silva,31,Female,Nelsonton,Refer Hospital,2014-11-21,Dr.B
233,234,Misty White,18,Female,South Scott,Cataract,2020-04-06,Dr.B
234,235,Keith Spears,49,Female,Lake Tracy,Cataract,2021-06-09,Dr.B
235,236,Andrew Allen,52,Male,Lake Annette,Cataract,1993-07-02,Dr.C
236,237,Gabriel Thomas,27,Female,Taylorburgh,Normal,1990-08-28,Dr.A
237,238,Sandra Myers,41,Male,Kristinstad,Normal,2023-04-01,Dr.C
238,239,Heather Lin,4,Male,Hughesmouth,Cataract,1992-11-04,Dr.B
239,240,James Reeves,23,Female,Donnashire,Refer Hospital,1975-12-27,Dr.C
240,241,Amy Pearson,53,Female,Garcialand,Normal,1987-12-09,Dr.A
241,242,Wendy Stephens,2,Female,North Lindseyhaven,Refer Hospital,2023-01-18,Dr.A
242,243,Cynthia Mcgee,10,Female,Joeltown,Normal,1986-07-15,Dr.A
243,244,Leslie Dillon,58,Male,Michaelaview,Refer Hospital,2025-12-15,Dr.C
244,245,Leonard Fitzpatrick,31,Male,East Andrewburgh,Cataract,1984-01-23,Dr.C
245,246,Nicholas Brown,53,Female,East Sarah,Cataract,2025-03-20,Dr.B
246,247,Adrienne Serrano,3,Male,North Jason,Cataract,1971-04-15,Dr.C
247,248,Terry Baldwin,51,Female,South Angelaview,Refer Hospital,2013-03-09,Dr.B
248,249,Jennifer Cox,39,Female,Port Helenview,Cataract,1989-08-09,Dr.B
249,250,Eddie Garrett,69,Male,Kennedyville,Cataract,2014-11-01,Dr.C
250,251,Danielle White,11,Male,Caseyland,Cataract,2003-11-13,Dr.A
251,252,Billy Fernandez,74,Male,North Jakeborough,Cataract,1994-01-12,Dr.A
252,253,Sarah Taylor,17,Male,Port Victor,Refer Hospital,2021-01-18,Dr.B
253,254,Sarah Clark,44,Female,New Isaac,Normal,2019-02-08,Dr.C
254,255,Jacob Robinson,70,Female,Pruittton,Cataract,1981-01-16,Dr.C
255,256,Louis Guerrero,52,Male,Lindsayfurt,Cataract,1977-06-20,Dr.C
256,257,Alexis Brooks,4,Male,South Cody,Cataract,2003-03-23,Dr.C
257,258,Shawn Richards,29,Male,North Michaelfurt,Normal,1997-03-30,Dr.B
258,259,Allison Webster,72,Male,New Garyville,Cataract,1984-05-06,Dr.A
259,260,Jared White,30,Male,Rodriguezstad,Cataract,2010-02-14,Dr.C
260,261,Amy Contreras,10,Female,New Barbarachester,Refer Hospital,1987-12-23,Dr.A
261,262,Crystal Gregory,47,Male,Port Ronaldville,Cataract,1975-09-04,Dr.A
262,263,Dana Perez,4,Male,Arellanoton,Cataract,1978-08-18,Dr.C
263,264,Daniel Hamilton,62,Male,Ortizfort,Cataract,1996-07-17,Dr.B
264,265,Wesley Davis,25,Male,Phamshire,Refer Hospital,2006-03-01,Dr.C
265,266,Terry Wong,76,Male,New Christinamouth,Normal,1982-07-22,Dr.A
266,267,Steven Lee,40,Female,Edwardsland,Cataract,2005-09-05,Dr.B
267,268,David Cruz,62,Female,Lake Rebecca,Refer Hospital,2006-01-06,Dr.C
268,269,George Huff,51,Male,Margaretberg,Cataract,1979-12-10,Dr.B
269,270,Janice Foster,14,Female,South Markside,Normal,1996-10-15,Dr.A
270,271,Darren Garrett,52,Female,Emilyfurt,Cataract,2008-12-17,Dr.A
271,272,Tyler Long,3,Female,Lake Carol,Normal,1999-05-29,Dr.C
272,273,Kimberly Jones,24,Female,East Jeffreyhaven,Refer Hospital,1992-08-21,Dr.B
273,274,Jeffrey Morgan,6,Female,East David,Refer Hospital,1996-07-25,Dr.C
274,275,Richard Jordan,22,Female,South Lisa,Normal,2002-03-23,Dr.C
275,276,David Riley,11,Male,Gillespieton,Cataract,1990-09-26,Dr.B
276,277,Justin Graves,63,Female,Glassfort,Normal,2008-03-08,Dr.A
277,278,Thomas Haney,61,Female,Williamstad,Cataract,1983-05-12,Dr.A
278,279,Cesar Garrett,21,Male,West Charles,Normal,1992-10-05,Dr.B
279,280,Tammy Johnson,57,Female,Mcintoshmouth,Cataract,1997-05-05,Dr.C
280,281,Kim Singh,24,Male,North Sheilamouth,Cataract,1993-10-18,Dr.C
281,282,Jose Petty,45,Female,Lyonsbury,Cataract,2022-12-28,Dr.C
282,283,Alexander Willis,30,Male,Colemanview,Refer Hospital,1984-11-15,Dr.B
283,284,Madison Decker,7,Female,North Andrea,Cataract,1980-03-17,Dr.B
284,285,Nicole Jones,71,Female,Matthewsstad,Refer Hospital,1973-03-08,Dr.B
285,286,Matthew Anderson,23,Male,Teresaburgh,Cataract,1991-02-17,Dr.C
286,287,Adrian Harper,39,Female,Dawnview,Refer Hospital,2000-01-10,Dr.C

In [39]:
#Data Collection (Load Excel Files)
emr = pd.read_excel("emr_data.xlsx")
camp = pd.read_excel("camp_data.xlsx")

print("EMR Data Shape:", emr.shape)
print("Camp Data Shape:", camp.shape)

emr.head()

EMR Data Shape: (500, 9)
Camp Data Shape: (500, 8)

,Patient_ID,Name,Age,Gender,Phone,Disease,Visit_Date,Doctor,Hospital
0,1,Stacy House,7,Male,(745)863-4849x80237,Cataract,1992-05-17,Dr.A,Eye Hospital
1,2,Joseph Schneider,75,Female,290.317.0166,Glaucoma,1986-05-30,Dr.A,Eye Hospital
2,3,Andrea Hill,22,Female,+1-369-508-8940x9297,Cataract,2000-12-01,Dr.B,Eye Hospital
3,4,Molly Davis,71,Male,(470)282-9036,Cataract,2013-11-25,Dr.B,Eye Hospital
4,5,Christopher Davis,2,Male,350.353.2089x061,Retina,1982-07-29,Dr.C,Eye Hospital

In [40]:
#Data Profiling
print("----- EMR INFO -----")
print(emr.info())

print("\n----- EMR STATISTICS -----")
print(emr.describe())

print("\n----- MISSING VALUES -----")
print(emr.isnull().sum())

----- EMR INFO -----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Patient_ID  500 non-null    int64
 1   Name        500 non-null    object
 2   Age         500 non-null    int64
 3   Gender      500 non-null    object
 4   Phone       500 non-null    object
 5   Disease     500 non-null    object
 6   Visit_Date  500 non-null    object
 7   Doctor      500 non-null    object
 8   Hospital    500 non-null    object
dtypes: int64(2), object(7)
memory usage: 35.3+ KB
None

----- EMR STATISTICS -----
       Patient_ID         Age
count  500.000000  500.000000
mean   250.500000   40.470000
std    144.481833   23.155939
min      1.000000    1.000000
25%    125.750000   21.000000
50%    250.500000   41.000000
75%    375.250000   60.000000
max    500.000000   80.000000

----- MISSING VALUES -----
Patient_ID    0
Name          0
Age           0
Gender        0
Phone         0
Disease       0
Visit_Date    0
Doctor        0
Hospital      0
dtype: int64

In [41]:
#camp data
print(camp.info())
print(camp.describe())
print(camp.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Camp_ID           500 non-null    int64
 1   Name              500 non-null    object
 2   Age               500 non-null    int64
 3   Gender            500 non-null    object
 4   Village           500 non-null    object
 5   Screening_Result  500 non-null    object
 6   Camp_Date         500 non-null    object
 7   Doctor            500 non-null    object
dtypes: int64(2), object(6)
memory usage: 31.4+ KB
None
          Camp_ID         Age
count  500.000000  500.000000
mean   250.500000   38.928000
std    144.481833   22.990867
min      1.000000    1.000000
25%    125.750000   19.000000
50%    250.500000   39.000000
75%    375.250000   57.000000
max    500.000000   80.000000
Camp_ID             0
Name                0
Age                 0
Gender              0
Village             0
Screening_Result    0
Camp_Date           0
Doctor              0
dtype: int64

In [24]:
# Handle missing values

emr["Age"] = emr["Age"].fillna(emr["Age"].mean())

emr["Name"] = emr["Name"].fillna("Unknown")

emr["Disease"] = emr["Disease"].fillna("Not Specified")

# Remove duplicate rows
emr = emr.drop_duplicates()

print("Data Cleaning Completed")

emr.head()

Data Cleaning Completed

,Patient_ID,Name,Age,Gender,Phone,Disease,Visit_Date,Doctor,Hospital
0,1,Stacy House,7,Male,(745)863-4849x80237,Cataract,1992-05-17,Dr.A,Eye Hospital
1,2,Joseph Schneider,75,Female,290.317.0166,Glaucoma,1986-05-30,Dr.A,Eye Hospital
2,3,Andrea Hill,22,Female,+1-369-508-8940x9297,Cataract,2000-12-01,Dr.B,Eye Hospital
3,4,Molly Davis,71,Male,(470)282-9036,Cataract,2013-11-25,Dr.B,Eye Hospital
4,5,Christopher Davis,2,Male,350.353.2089x061,Retina,1982-07-29,Dr.C,Eye Hospital

In [25]:
emr.isnull().sum()

Patient_ID    0
Name          0
Age           0
Gender        0
Phone         0
Disease       0
Visit_Date    0
Doctor        0
Hospital      0
dtype: int64

In [42]:
#Schema Design
schema = {
"Patient_ID":"Integer",
"Name":"String",
"Age":"Integer",
"Gender":"String",
"Phone":"String",
"Disease":"String",
"Visit_Date":"Date",
"Doctor":"String",
"Hospital":"String"
}

print("Schema Design")
print(schema)

Schema Design
{'Patient_ID': 'Integer', 'Name': 'String', 'Age': 'Integer', 'Gender': 'String', 'Phone': 'String', 'Disease': 'String', 'Visit_Date': 'Date', 'Doctor': 'String', 'Hospital': 'String'}

In [43]:
#Data Mapping (Camp → Hospital)
mapping = {
"Name":"Name",
"Age":"Age",
"Gender":"Gender",
"Camp_Date":"Visit_Date",
"Doctor":"Doctor"
}

print("Data Mapping")
print(mapping)

Data Mapping
{'Name': 'Name', 'Age': 'Age', 'Gender': 'Gender', 'Camp_Date': 'Visit_Date', 'Doctor': 'Doctor'}

In [44]:
#ETL Pipeline
def extract():
    emr = pd.read_excel("emr_data.xlsx")
    camp = pd.read_excel("camp_data.xlsx")
    return emr, camp

In [35]:
# Transform
def transform(emr, camp):

    emr = emr.drop_duplicates()
    camp = camp.drop_duplicates()

    emr["Age"] = emr["Age"].fillna(emr["Age"].mean())
    camp["Age"] = camp["Age"].fillna(camp["Age"].mean())

    return emr, camp

In [36]:
def load(emr,camp):

    emr.to_csv("clean_emr_data.csv",index=False)

    camp.to_csv("clean_camp_data.csv",index=False)

    print("ETL Process Completed Successfully")

In [46]:
#Run ETL Pipeline
emr,camp = extract()

emr_clean,camp_clean = transform(emr,camp)

load(emr_clean,camp_clean)

ETL Process Completed Successfully

In [47]:
#Testing ETL
test = pd.read_csv("clean_emr_data.csv")

print(test.head())

print("Rows:",test.shape)

   Patient_ID               Name  Age  Gender                 Phone   Disease  \
0           1        Stacy House    7    Male   (745)863-4849x80237  Cataract
1           2   Joseph Schneider   75  Female          290.317.0166  Glaucoma
2           3        Andrea Hill   22  Female  +1-369-508-8940x9297  Cataract
3           4        Molly Davis   71    Male         (470)282-9036  Cataract
4           5  Christopher Davis    2    Male      350.353.2089x061    Retina

   Visit_Date Doctor      Hospital
0  1992-05-17   Dr.A  Eye Hospital
1  1986-05-30   Dr.A  Eye Hospital
2  2000-12-01   Dr.B  Eye Hospital
3  2013-11-25   Dr.B  Eye Hospital
4  1982-07-29   Dr.C  Eye Hospital
Rows: (500, 9)